from base import BaseAgent
from actions import ACTIONS


class BasicStrategyAgent(BaseAgent):

      def __init__(self):

            self.basic_strategy_policy = {
                  #HARD HANDS
                  (16,1,False,False): ACTIONS.hit,
                  (16,2,False,False): ACTIONS.stand,
                  (16,3,False,False): ACTIONS.stand,
                  (16,4,False,False): ACTIONS.stand,
                  (16,5,False,False): ACTIONS.stand,
                  (16,6,False,False): ACTIONS.stand,
                  (16,7,False,False): ACTIONS.hit,
                  (16,8,False,False): ACTIONS.hit,
                  (16,9,False,False): ACTIONS.hit,
                  (16,10,False,False): ACTIONS.hit,

                  (15,1,False,False): ACTIONS.hit,
                  (15,2,False,False): ACTIONS.stand,
                  (15,3,False,False): ACTIONS.stand,
                  (15,4,False,False): ACTIONS.stand,
                  (15,5,False,False): ACTIONS.stand,
                  (15,6,False,False): ACTIONS.stand,
                  (15,7,False,False): ACTIONS.hit,
                  (15,8,False,False): ACTIONS.hit,
                  (15,9,False,False): ACTIONS.hit,
                  (15,10,False,False): ACTIONS.hit,

                  (14,1,False,False): ACTIONS.hit,
                  (14,2,False,False): ACTIONS.stand,
                  (14,3,False,False): ACTIONS.stand,
                  (14,4,False,False): ACTIONS.stand,
                  (14,5,False,False): ACTIONS.stand,
                  (14,6,False,False): ACTIONS.stand,
                  (14,7,False,False): ACTIONS.hit,
                  (14,8,False,False): ACTIONS.hit,
                  (14,9,False,False): ACTIONS.hit,
                  (14,10,False,False): ACTIONS.hit,

                  (13,1,False,False): ACTIONS.hit,
                  (13,2,False,False): ACTIONS.stand,
                  (13,3,False,False): ACTIONS.stand,
                  (13,4,False,False): ACTIONS.stand,
                  (13,5,False,False): ACTIONS.stand,
                  (13,6,False,False): ACTIONS.stand,
                  (13,7,False,False): ACTIONS.hit,
                  (13,8,False,False): ACTIONS.hit,
                  (13,9,False,False): ACTIONS.hit,
                  (13,10,False,False): ACTIONS.hit,

                  (12,1,False,False): ACTIONS.hit,
                  (12,2,False,False): ACTIONS.hit,
                  (12,3,False,False): ACTIONS.hit,
                  (12,4,False,False): ACTIONS.stand,
                  (12,5,False,False): ACTIONS.stand,
                  (12,6,False,False): ACTIONS.stand,
                  (12,7,False,False): ACTIONS.hit,
                  (12,8,False,False): ACTIONS.hit,
                  (12,9,False,False): ACTIONS.hit,
                  (12,10,False,False): ACTIONS.hit,

                  (11,1,False,False): ACTIONS.hit,
                  (11,2,False,False): ACTIONS.double,
                  (11,3,False,False): ACTIONS.double,
                  (11,4,False,False): ACTIONS.double,
                  (11,5,False,False): ACTIONS.double,
                  (11,6,False,False): ACTIONS.double,
                  (11,7,False,False): ACTIONS.double,
                  (11,8,False,False): ACTIONS.double,
                  (11,9,False,False): ACTIONS.double,
                  (11,10,False,False): ACTIONS.double,

                  (10,1,False,False): ACTIONS.hit,
                  (10,2,False,False): ACTIONS.double,
                  (10,3,False,False): ACTIONS.double,
                  (10,4,False,False): ACTIONS.double,
                  (10,5,False,False): ACTIONS.double,
                  (10,6,False,False): ACTIONS.double,
                  (10,7,False,False): ACTIONS.double,
                  (10,8,False,False): ACTIONS.double,
                  (10,9,False,False): ACTIONS.double,
                  (10,10,False,False): ACTIONS.hit,

                  (9,1,False,False): ACTIONS.hit,
                  (9,2,False,False): ACTIONS.hit,
                  (9,3,False,False): ACTIONS.double,
                  (9,4,False,False): ACTIONS.double,
                  (9,5,False,False): ACTIONS.double,
                  (9,6,False,False): ACTIONS.double,
                  (9,7,False,False): ACTIONS.hit,
                  (9,8,False,False): ACTIONS.hit,
                  (9,9,False,False): ACTIONS.hit,
                  (9,10,False,False): ACTIONS.hit,

                  (8,1,False,False): ACTIONS.hit,
                  (8,2,False,False): ACTIONS.hit,
                  (8,3,False,False): ACTIONS.hit,
                  (8,4,False,False): ACTIONS.hit,
                  (8,5,False,False): ACTIONS.hit,
                  (8,6,False,False): ACTIONS.hit,
                  (8,7,False,False): ACTIONS.hit,
                  (8,8,False,False): ACTIONS.hit,
                  (8,9,False,False): ACTIONS.hit,
                  (8,10,False,False): ACTIONS.hit,

                  (7,1,False,False): ACTIONS.hit,
                  (7,2,False,False): ACTIONS.hit,
                  (7,3,False,False): ACTIONS.hit,
                  (7,4,False,False): ACTIONS.hit,
                  (7,5,False,False): ACTIONS.hit,
                  (7,6,False,False): ACTIONS.hit,
                  (7,7,False,False): ACTIONS.hit,
                  (7,8,False,False): ACTIONS.hit,
                  (7,9,False,False): ACTIONS.hit,
                  (7,10,False,False): ACTIONS.hit,

                  (6,1,False,False): ACTIONS.hit,
                  (6,2,False,False): ACTIONS.hit,
                  (6,3,False,False): ACTIONS.hit,
                  (6,4,False,False): ACTIONS.hit,
                  (6,5,False,False): ACTIONS.hit,
                  (6,6,False,False): ACTIONS.hit,
                  (6,7,False,False): ACTIONS.hit,
                  (6,8,False,False): ACTIONS.hit,
                  (6,9,False,False): ACTIONS.hit,
                  (6,10,False,False): ACTIONS.hit,

                  (5,1,False,False): ACTIONS.hit,
                  (5,2,False,False): ACTIONS.hit,
                  (5,3,False,False): ACTIONS.hit,
                  (5,4,False,False): ACTIONS.hit,
                  (5,5,False,False): ACTIONS.hit,
                  (5,6,False,False): ACTIONS.hit,
                  (5,7,False,False): ACTIONS.hit,
                  (5,8,False,False): ACTIONS.hit,
                  (5,9,False,False): ACTIONS.hit,
                  (5,10,False,False): ACTIONS.hit,
                  #SOFT HANDS
                  #18 (ace + 7)
                  (18,1,True,False): ACTIONS.hit,
                  (18,2,True,False): ACTIONS.stand,
                  (18,3,True,False): ACTIONS.double,
                  (18,4,True,False): ACTIONS.double,
                  (18,5,True,False): ACTIONS.double,
                  (18,6,True,False): ACTIONS.double,
                  (18,7,True,False): ACTIONS.stand,
                  (18,8,True,False): ACTIONS.stand,
                  (18,9,True,False): ACTIONS.hit,
                  (18,10,True,False): ACTIONS.hit,
                  #17 (ace + 6)
                  (17,1,True,False): ACTIONS.hit,
                  (17,2,True,False): ACTIONS.hit,
                  (17,3,True,False): ACTIONS.double,
                  (17,4,True,False): ACTIONS.double,
                  (17,5,True,False): ACTIONS.double,
                  (17,6,True,False): ACTIONS.double,
                  (17,7,True,False): ACTIONS.hit,
                  (17,8,True,False): ACTIONS.hit,
                  (17,9,True,False): ACTIONS.hit,
                  (17,10,True,False): ACTIONS.hit,
                  #16 (ace + 5)
                  (16,1,True,False): ACTIONS.hit,
                  (16,2,True,False): ACTIONS.hit,
                  (16,3,True,False): ACTIONS.hit,
                  (16,4,True,False): ACTIONS.double,
                  (16,5,True,False): ACTIONS.double,
                  (16,6,True,False): ACTIONS.double,
                  (16,7,True,False): ACTIONS.hit,
                  (16,8,True,False): ACTIONS.hit,
                  (16,9,True,False): ACTIONS.hit,
                  (16,10,True,False): ACTIONS.hit,
                  #15 (ace + 4)
                  (15,1,True,False): ACTIONS.hit,
                  (15,2,True,False): ACTIONS.hit,
                  (15,3,True,False): ACTIONS.hit,
                  (15,4,True,False): ACTIONS.double,
                  (15,5,True,False): ACTIONS.double,
                  (15,6,True,False): ACTIONS.double,
                  (15,7,True,False): ACTIONS.hit,
                  (15,8,True,False): ACTIONS.hit,
                  (15,9,True,False): ACTIONS.hit,
                  (15,10,True,False): ACTIONS.hit,
                  #14 (ace + 3)
                  (14,1,True,False): ACTIONS.hit,
                  (14,2,True,False): ACTIONS.hit,
                  (14,3,True,False): ACTIONS.hit,
                  (14,4,True,False): ACTIONS.hit,
                  (14,5,True,False): ACTIONS.double,
                  (14,6,True,False): ACTIONS.double,
                  (14,7,True,False): ACTIONS.hit,
                  (14,8,True,False): ACTIONS.hit,
                  (14,9,True,False): ACTIONS.hit,
                  (14,10,True,False): ACTIONS.hit,
                  #13 (ace + 2)
                  (13,1,True,False): ACTIONS.hit,
                  (13,2,True,False): ACTIONS.hit,
                  (13,3,True,False): ACTIONS.hit,
                  (13,4,True,False): ACTIONS.hit,
                  (13,5,True,False): ACTIONS.double,
                  (13,6,True,False): ACTIONS.double,
                  (13,7,True,False): ACTIONS.hit,
                  (13,8,True,False): ACTIONS.hit,
                  (13,9,True,False): ACTIONS.hit,
                  (13,10,True,False): ACTIONS.hit,
                  #Can split Hands
                  #2 aces
                  (2,1,False,True): ACTIONS.split,
                  (2,2,False,True): ACTIONS.split,
                  (2,3,False,True): ACTIONS.split,
                  (2,4,False,True): ACTIONS.split,
                  (2,5,False,True): ACTIONS.split,
                  (2,6,False,True): ACTIONS.split,
                  (2,7,False,True): ACTIONS.split,
                  (2,8,False,True): ACTIONS.split,
                  (2,9,False,True): ACTIONS.split,
                  (2,10,False,True): ACTIONS.split,
                  #2 eights
                  (16,1,False,True): ACTIONS.split,
                  (16,2,False,True): ACTIONS.split,
                  (16,3,False,True): ACTIONS.split,
                  (16,4,False,True): ACTIONS.split,
                  (16,5,False,True): ACTIONS.split,
                  (16,6,False,True): ACTIONS.split,
                  (16,7,False,True): ACTIONS.split,
                  (16,8,False,True): ACTIONS.split,
                  (16,9,False,True): ACTIONS.split,
                  (16,10,False,True): ACTIONS.split,
                  #2 figures or 10s
                  (20,1,False,True): ACTIONS.stand,
                  (20,2,False,True): ACTIONS.stand,
                  (20,3,False,True): ACTIONS.stand,
                  (20,4,False,True): ACTIONS.stand,
                  (20,5,False,True): ACTIONS.stand,
                  (20,6,False,True): ACTIONS.stand,
                  (20,7,False,True): ACTIONS.stand,
                  (20,8,False,True): ACTIONS.stand,
                  (20,9,False,True): ACTIONS.stand,
                  (20,10,False,True): ACTIONS.stand,
                  #2 nines
                  (18,1,False,True): ACTIONS.stand,
                  (18,2,False,True): ACTIONS.split,
                  (18,3,False,True): ACTIONS.split,
                  (18,4,False,True): ACTIONS.split,
                  (18,5,False,True): ACTIONS.split,
                  (18,6,False,True): ACTIONS.split,
                  (18,7,False,True): ACTIONS.stand,
                  (18,8,False,True): ACTIONS.split,
                  (18,9,False,True): ACTIONS.split,
                  (18,10,False,True): ACTIONS.stand,
                  #2 sevens
                  (14,1,False,True): ACTIONS.hit,
                  (14,2,False,True): ACTIONS.split,
                  (14,3,False,True): ACTIONS.split,
                  (14,4,False,True): ACTIONS.split,
                  (14,5,False,True): ACTIONS.split,
                  (14,6,False,True): ACTIONS.split,
                  (14,7,False,True): ACTIONS.split,
                  (14,8,False,True): ACTIONS.hit,
                  (14,9,False,True): ACTIONS.hit,
                  (14,10,False,True): ACTIONS.hit,
                  #2 sixes
                  (12,1,False,True): ACTIONS.hit,
                  (12,2,False,True): ACTIONS.split,
                  (12,3,False,True): ACTIONS.split,
                  (12,4,False,True): ACTIONS.split,
                  (12,5,False,True): ACTIONS.split,
                  (12,6,False,True): ACTIONS.split,
                  (12,7,False,True): ACTIONS.hit,
                  (12,8,False,True): ACTIONS.hit,
                  (12,9,False,True): ACTIONS.hit,
                  (12,10,False,True): ACTIONS.hit,
                  #2 fives
                  (10,1,False,True): ACTIONS.hit,
                  (10,2,False,True): ACTIONS.double,
                  (10,3,False,True): ACTIONS.double,
                  (10,4,False,True): ACTIONS.double,
                  (10,5,False,True): ACTIONS.double,
                  (10,6,False,True): ACTIONS.double,
                  (10,7,False,True): ACTIONS.double,
                  (10,8,False,True): ACTIONS.double,
                  (10,9,False,True): ACTIONS.double,
                  (10,10,False,True): ACTIONS.hit,
                  #2 fours
                  (8,1,False,True): ACTIONS.hit,
                  (8,2,False,True): ACTIONS.hit,
                  (8,3,False,True): ACTIONS.hit,
                  (8,4,False,True): ACTIONS.hit,
                  (8,5,False,True): ACTIONS.split,
                  (8,6,False,True): ACTIONS.split,
                  (8,7,False,True): ACTIONS.hit,
                  (8,8,False,True): ACTIONS.hit,
                  (8,9,False,True): ACTIONS.hit,
                  (8,10,False,True): ACTIONS.hit,
                  #2 threes
                  (6,1,False,True): ACTIONS.hit,
                  (6,2,False,True): ACTIONS.split,
                  (6,3,False,True): ACTIONS.split,
                  (6,4,False,True): ACTIONS.split,
                  (6,5,False,True): ACTIONS.split,
                  (6,6,False,True): ACTIONS.split,
                  (6,7,False,True): ACTIONS.split,
                  (6,8,False,True): ACTIONS.hit,
                  (6,9,False,True): ACTIONS.hit,
                  (6,10,False,True): ACTIONS.hit,
                  #2 twos
                  (4,1,False,True): ACTIONS.hit,
                  (4,2,False,True): ACTIONS.split,
                  (4,3,False,True): ACTIONS.split,
                  (4,4,False,True): ACTIONS.split,
                  (4,5,False,True): ACTIONS.split,
                  (4,6,False,True): ACTIONS.split,
                  (4,7,False,True): ACTIONS.split,
                  (4,8,False,True): ACTIONS.hit,
                  (4,9,False,True): ACTIONS.hit,
                  (4,10,False,True): ACTIONS.hit,
            }

      def get_action(self, player_hand, house_up_card):

            if not player_hand.is_soft() and player_hand.score() >= 17:
                  return ACTIONS.stand
            elif player_hand.is_soft() and player_hand.score() >= 19:
                  return ACTIONS.stand

            state = (player_hand.score(), house_up_card, player_hand.is_soft(), player_hand.can_split())
            action = self.basic_strategy_policy[state]

            return action
